### ISSUE TITLE
Will it support a video output?

### ISSUE THREAD

**Issue by BenjiKCF** [DAVIDNYARKO123/yolov8-silva#1]
Thanks for your implementation, since the official support for numpy array is not here yet, I see why you have to write frame and read it one by one.  Do you plan to make a cv2.VideoWriter for the inference in the future?
 
https://docs.ultralytics.com/python/

Thank you so much

**Comment by DAVIDNYARKO123** [comment]
Thank you for the input, I will add video output to the TODO list
